import os
from datetime import date
from decimal import Decimal
import pytest
from ashare.models.financial_report import (
    FinancialReport,
    IncomeStatement,
    BalanceSheet,
    CashFlowStatement,
    FinancialIndicators
)
from ashare.models.financial_report_repository import FinancialReportRepository

@pytest.fixture
def db_path():
    path = "/Users/kentpeng/learning/fin_mgr1/tests/test.db"
    yield path
    # 测试结束后删除数据库文件
    if os.path.exists(path):
        os.remove(path)

@pytest.fixture
def repository(db_path):
    return FinancialReportRepository(db_path)

@pytest.fixture
def sample_report():
    # 创建测试用的财务报告数据
    income_statement = IncomeStatement(
        ts_code="000001.SZ",
        ann_date=date(2023, 4, 25),
        f_ann_date=date(2023, 4, 25),
        end_date=date(2023, 3, 31),
        report_type="1",
        comp_type="1",
        end_type="1",
        basic_eps=Decimal("0.5"),
        diluted_eps=Decimal("0.5"),
        total_revenue=Decimal("1000000"),
        revenue=Decimal("900000"),
        int_income=Decimal("0"),
        prem_earned=Decimal("0"),
        comm_income=Decimal("0"),
        n_commis_income=Decimal("0"),
        n_oth_income=Decimal("0"),
        n_oth_b_income=Decimal("0"),
        prem_income=Decimal("0"),
        out_prem=Decimal("0"),
        une_prem_reser=Decimal("0"),
        reins_income=Decimal("0"),
        n_sec_tb_income=Decimal("0"),
        n_sec_uw_income=Decimal("0"),
        n_asset_mg_income=Decimal("0"),
        oth_b_income=Decimal("0"),
        fv_value_chg_gain=Decimal("0"),
        invest_income=Decimal("0"),
        ass_invest_income=Decimal("0"),
        forex_gain=Decimal("0"),
        total_cogs=Decimal("0"),
        oper_cost=Decimal("0"),
        int_exp=Decimal("0"),
        comm_exp=Decimal("0"),
        biz_tax_surchg=Decimal("0"),
        sell_exp=Decimal("0"),
        admin_exp=Decimal("0"),
        fin_exp=Decimal("0"),
        assets_impair_loss=Decimal("0"),
        prem_refund=Decimal("0"),
        compens_payout=Decimal("0"),
        reser_insur_liab=Decimal("0"),
        div_payt=Decimal("0"),
        reins_exp=Decimal("0"),
        oper_exp=Decimal("0"),
        compens_payout_refu=Decimal("0"),
        insur_reser_refu=Decimal("0"),
        reins_cost_refund=Decimal("0"),
        other_bus_cost=Decimal("0"),
        operate_profit=Decimal("0"),
        non_oper_income=Decimal("0"),
        non_oper_exp=Decimal("0"),
        nca_disploss=Decimal("0"),
        total_profit=Decimal("0"),
        income_tax=Decimal("0"),
        n_income=Decimal("0"),
        n_income_attr_p=Decimal("0"),
        minority_gain=Decimal("0"),
        oth_compr_income=Decimal("0"),
        t_compr_income=Decimal("0"),
        compr_inc_attr_p=Decimal("0"),
        compr_inc_attr_m_s=Decimal("0"),
        ebit=Decimal("0"),
        ebitda=Decimal("0"),
        insurance_exp=Decimal("0"),
        undist_profit=Decimal("0"),
        distable_profit=Decimal("0"),
        rd_exp=Decimal("0"),
        fin_exp_int_exp=Decimal("0"),
        fin_exp_int_inc=Decimal("0"),
        transfer_surplus_rese=Decimal("0"),
        transfer_housing_imprest=Decimal("0"),
        transfer_oth=Decimal("0"),
        adj_lossgain=Decimal("0"),
        withdra_legal_surplus=Decimal("0"),
        withdra_legal_pubfund=Decimal("0"),
        withdra_biz_devfund=Decimal("0"),
        withdra_rese_fund=Decimal("0"),
        withdra_oth_ersu=Decimal("0"),
        workers_welfare=Decimal("0"),
        distr_profit_shrhder=Decimal("0"),
        prfshare_payable_dvd=Decimal("0"),
        comshare_payable_dvd=Decimal("0"),
        capit_comstock_div=Decimal("0"),
        net_after_nr_lp_correct=Decimal("0"),
        credit_impa_loss=Decimal("0"),
        net_expo_hedging_benefits=Decimal("0"),
        oth_impair_loss_assets=Decimal("0"),
        total_opcost=Decimal("0"),
        amodcost_fin_assets=Decimal("0"),
        oth_income=Decimal("0"),
        asset_disp_income=Decimal("0"),
        continued_net_profit=Decimal("0"),
        end_net_profit=Decimal("0"),
        update_flag="1"
    )

    balance_sheet = BalanceSheet(
        ts_code="000001.SZ",
        ann_date=date(2023, 4, 25),
        f_ann_date=date(2023, 4, 25),
        end_date=date(2023, 3, 31),
        report_type="1",
        comp_type="1",
        end_type="1",
        total_share=Decimal("1000000"),
        money_cap=Decimal("500000"),
        total_assets=Decimal("2000000"),
        total_liab=Decimal("1000000"),
        cap_rese=Decimal("0"),
        undistr_porfit=Decimal("0"),
        surplus_rese=Decimal("0"),
        special_rese=Decimal("0"),
        trad_asset=Decimal("0"),
        notes_receiv=Decimal("0"),
        accounts_receiv=Decimal("0"),
        oth_receiv=Decimal("0"),
        prepayment=Decimal("0"),
        div_receiv=Decimal("0"),
        int_receiv=Decimal("0"),
        inventories=Decimal("0"),
        amor_exp=Decimal("0"),
        nca_within_1y=Decimal("0"),
        sett_rsrv=Decimal("0"),
        loanto_oth_bank_fi=Decimal("0"),
        premium_receiv=Decimal("0"),
        reinsur_receiv=Decimal("0"),
        reinsur_res_receiv=Decimal("0"),
        pur_resale_fa=Decimal("0"),
        oth_cur_assets=Decimal("0"),
        total_cur_assets=Decimal("0"),
        fa_avail_for_sale=Decimal("0"),
        htm_invest=Decimal("0"),
        lt_eqt_invest=Decimal("0"),
        invest_real_estate=Decimal("0"),
        time_deposits=Decimal("0"),
        oth_assets=Decimal("0"),
        lt_rec=Decimal("0"),
        fix_assets=Decimal("0"),
        cip=Decimal("0"),
        const_materials=Decimal("0"),
        fixed_assets_disp=Decimal("0"),
        produc_bio_assets=Decimal("0"),
        oil_and_gas_assets=Decimal("0"),
        intan_assets=Decimal("0"),
        r_and_d=Decimal("0"),
        goodwill=Decimal("0"),
        lt_amor_exp=Decimal("0"),
        defer_tax_assets=Decimal("0"),
        decr_in_disbur=Decimal("0"),
        oth_nca=Decimal("0"),
        total_nca=Decimal("0"),
        cash_reser_cb=Decimal("0"),
        depos_in_oth_bfi=Decimal("0"),
        prec_metals=Decimal("0"),
        deriv_assets=Decimal("0"),
        rr_reins_une_prem=Decimal("0"),
        rr_reins_outstd_cla=Decimal("0"),
        rr_reins_lins_liab=Decimal("0"),
        rr_reins_lthins_liab=Decimal("0"),
        refund_depos=Decimal("0"),
        ph_pledge_loans=Decimal("0"),
        refund_cap_depos=Decimal("0"),
        indep_acct_assets=Decimal("0"),
        client_depos=Decimal("0"),
        client_prov=Decimal("0"),
        transac_seat_fee=Decimal("0"),
        invest_as_receiv=Decimal("0"),
        lt_borr=Decimal("0"),
        st_borr=Decimal("0"),
        cb_borr=Decimal("0"),
        depos_ib_deposits=Decimal("0"),
        loan_oth_bank=Decimal("0"),
        trading_fl=Decimal("0"),
        notes_payable=Decimal("0"),
        acct_payable=Decimal("0"),
        adv_receipts=Decimal("0"),
        sold_for_repur_fa=Decimal("0"),
        comm_payable=Decimal("0"),
        payroll_payable=Decimal("0"),
        taxes_payable=Decimal("0"),
        int_payable=Decimal("0"),
        div_payable=Decimal("0"),
        oth_payable=Decimal("0"),
        acc_exp=Decimal("0"),
        deferred_inc=Decimal("0"),
        st_bonds_payable=Decimal("0"),
        payable_to_reinsurer=Decimal("0"),
        rsrv_insur_cont=Decimal("0"),
        acting_trading_sec=Decimal("0"),
        acting_uw_sec=Decimal("0"),
        non_cur_liab_due_1y=Decimal("0"),
        oth_cur_liab=Decimal("0"),
        total_cur_liab=Decimal("0"),
        bond_payable=Decimal("0"),
        lt_payable=Decimal("0"),
        specific_payables=Decimal("0"),
        estimated_liab=Decimal("0"),
        defer_tax_liab=Decimal("0"),
        defer_inc_non_cur_liab=Decimal("0"),
        oth_ncl=Decimal("0"),
        total_ncl=Decimal("0"),
        depos_oth_bfi=Decimal("0"),
        deriv_liab=Decimal("0"),
        depos=Decimal("0"),
        agency_bus_liab=Decimal("0"),
        oth_liab=Decimal("0"),
        prem_receiv_adva=Decimal("0"),
        depos_received=Decimal("0"),
        ph_invest=Decimal("0"),
        reser_une_prem=Decimal("0"),
        reser_outstd_claims=Decimal("0"),
        reser_lins_liab=Decimal("0"),
        reser_lthins_liab=Decimal("0"),
        indept_acc_liab=Decimal("0"),
        pledge_borr=Decimal("0"),
        indem_payable=Decimal("0"),
        policy_div_payable=Decimal("0"),
        treasury_share=Decimal("0"),
        ordin_risk_reser=Decimal("0"),
        forex_differ=Decimal("0"),
        invest_loss_unconf=Decimal("0"),
        minority_int=Decimal("0"),
        total_hldr_eqy_exc_min_int=Decimal("0"),
        total_hldr_eqy_inc_min_int=Decimal("0"),
        total_liab_hldr_eqy=Decimal("0"),
        lt_payroll_payable=Decimal("0"),
        oth_comp_income=Decimal("0"),
        oth_eqt_tools=Decimal("0"),
        oth_eqt_tools_p_shr=Decimal("0"),
        lending_funds=Decimal("0"),
        acc_receivable=Decimal("0"),
        st_fin_payable=Decimal("0"),
        payables=Decimal("0"),
        hfs_assets=Decimal("0"),
        hfs_sales=Decimal("0"),
        cost_fin_assets=Decimal("0"),
        fair_value_fin_assets=Decimal("0"),
        cip_total=Decimal("0"),
        oth_pay_total=Decimal("0"),
        long_pay_total=Decimal("0"),
        debt_invest=Decimal("0"),
        oth_debt_invest=Decimal("0"),
        oth_eq_invest=Decimal("0"),
        oth_illiq_fin_assets=Decimal("0"),
        oth_eq_ppbond=Decimal("0"),
        receiv_financing=Decimal("0"),
        use_right_assets=Decimal("0"),
        lease_liab=Decimal("0"),
        contract_assets=Decimal("0"),
        contract_liab=Decimal("0"),
        accounts_receiv_bill=Decimal("0"),
        accounts_pay=Decimal("0"),
        oth_rcv_total=Decimal("0"),
        fix_assets_total=Decimal("0"),
        update_flag="1"
    )

    cash_flow_statement = CashFlowStatement(
        ts_code="000001.SZ",
        ann_date=date(2023, 4, 25),  # 修改为 date 对象
        f_ann_date=date(2023, 4, 25),
        end_date=date(2023, 3, 31),
        comp_type="1",
        report_type="1",
        end_type="1",
        net_profit=Decimal("100000"),
        finan_exp=Decimal("0"),
        c_fr_sale_sg=Decimal("0"),
        recp_tax_rends=Decimal("0"),
        n_depos_incr_fi=Decimal("0"),
        n_incr_loans_cb=Decimal("0"),
        n_inc_borr_oth_fi=Decimal("0"),
        prem_fr_orig_contr=Decimal("0"),
        n_incr_insured_dep=Decimal("0"),
        n_reinsur_prem=Decimal("0"),
        n_incr_disp_tfa=Decimal("0"),
        ifc_cash_incr=Decimal("0"),
        n_incr_disp_faas=Decimal("0"),
        n_incr_loans_oth_bank=Decimal("0"),
        n_cap_incr_repur=Decimal("0"),
        c_fr_oth_operate_a=Decimal("0"),
        c_inf_fr_operate_a=Decimal("0"),
        c_paid_goods_s=Decimal("0"),
        c_paid_to_for_empl=Decimal("0"),
        c_paid_for_taxes=Decimal("0"),
        n_incr_clt_loan_adv=Decimal("0"),
        n_incr_dep_cbob=Decimal("0"),
        c_pay_claims_orig_inco=Decimal("0"),
        pay_handling_chrg=Decimal("0"),
        pay_comm_insur_plcy=Decimal("0"),
        oth_cash_pay_oper_act=Decimal("0"),
        st_cash_out_act=Decimal("0"),
        n_cashflow_act=Decimal("0"),
        oth_recp_ral_inv_act=Decimal("0"),
        c_disp_withdrwl_invest=Decimal("0"),
        c_recp_return_invest=Decimal("0"),
        n_recp_disp_fiolta=Decimal("0"),
        n_recp_disp_sobu=Decimal("0"),
        stot_inflows_inv_act=Decimal("0"),
        c_pay_acq_const_fiolta=Decimal("0"),
        c_paid_invest=Decimal("0"),
        n_disp_subs_oth_biz=Decimal("0"),
        oth_pay_ral_inv_act=Decimal("0"),
        n_incr_pledge_loan=Decimal("0"),
        stot_out_inv_act=Decimal("0"),
        n_cashflow_inv_act=Decimal("0"),
        c_recp_borrow=Decimal("0"),
        proc_issue_bonds=Decimal("0"),
        oth_cash_recp_ral_fnc_act=Decimal("0"),
        stot_cash_in_fnc_act=Decimal("0"),
        free_cashflow=Decimal("0"),
        c_prepay_amt_borr=Decimal("0"),
        c_pay_dist_dpcp_int_exp=Decimal("0"),
        incl_dvd_profit_paid_sc_ms=Decimal("0"),
        oth_cashpay_ral_fnc_act=Decimal("0"),
        stot_cashout_fnc_act=Decimal("0"),
        n_cash_flows_fnc_act=Decimal("0"),
        eff_fx_flu_cash=Decimal("0"),
        n_incr_cash_cash_equ=Decimal("0"),
        c_cash_equ_beg_period=Decimal("0"),
        c_cash_equ_end_period=Decimal("0"),
        c_recp_cap_contrib=Decimal("0"),
        incl_cash_rec_saims=Decimal("0"),
        uncon_invest_loss=Decimal("0"),
        prov_depr_assets=Decimal("0"),
        depr_fa_coga_dpba=Decimal("0"),
        amort_intang_assets=Decimal("0"),
        lt_amort_deferred_exp=Decimal("0"),
        decr_deferred_exp=Decimal("0"),
        incr_acc_exp=Decimal("0"),
        loss_disp_fiolta=Decimal("0"),
        loss_scr_fa=Decimal("0"),
        loss_fv_chg=Decimal("0"),
        invest_loss=Decimal("0"),
        decr_def_inc_tax_assets=Decimal("0"),
        incr_def_inc_tax_liab=Decimal("0"),
        decr_inventories=Decimal("0"),
        decr_oper_payable=Decimal("0"),
        incr_oper_payable=Decimal("0"),
        others=Decimal("0"),
        im_net_cashflow_oper_act=Decimal("0"),
        conv_debt_into_cap=Decimal("0"),
        conv_copbonds_due_within_1y=Decimal("0"),
        fa_fnc_leases=Decimal("0"),
        im_n_incr_cash_equ=Decimal("0"),
        net_dism_capital_add=Decimal("0"),
        net_cash_rece_sec=Decimal("0"),
        credit_impa_loss=Decimal("0"),
        use_right_asset_dep=Decimal("0"),
        oth_loss_asset=Decimal("0"),
        end_bal_cash=Decimal("0"),
        beg_bal_cash=Decimal("0"),
        end_bal_cash_equ=Decimal("0"),
        beg_bal_cash_equ=Decimal("0"),
        update_flag="1"
    )

    financial_indicators = FinancialIndicators(
        ts_code="000001.SZ",
        ann_date=date(2023, 4, 25),
        end_date=date(2023, 3, 31),
        eps=Decimal("0.5"),
        dt_eps=Decimal("0.5"),
        total_revenue_ps=Decimal("10.0"),
        revenue_ps=Decimal("0"),
        capital_rese_ps=Decimal("0"),
        surplus_rese_ps=Decimal("0"),
        undist_profit_ps=Decimal("0"),
        extra_item=Decimal("0"),
        profit_dedt=Decimal("0"),
        gross_margin=Decimal("0"),
        current_ratio=Decimal("0"),
        quick_ratio=Decimal("0"),
        cash_ratio=Decimal("0"),
        invturn_days=Decimal("0"),
        arturn_days=Decimal("0"),
        inv_turn=Decimal("0"),
        ar_turn=Decimal("0"),
        ca_turn=Decimal("0"),
        fa_turn=Decimal("0"),
        assets_turn=Decimal("0"),
        op_income=Decimal("0"),
        valuechange_income=Decimal("0"),
        interst_income=Decimal("0"),
        daa=Decimal("0"),
        ebit=Decimal("0"),
        ebitda=Decimal("0"),
        fcff=Decimal("0"),
        fcfe=Decimal("0"),
        current_exint=Decimal("0"),
        noncurrent_exint=Decimal("0"),
        interestdebt=Decimal("0"),
        netdebt=Decimal("0"),
        tangible_asset=Decimal("0"),
        working_capital=Decimal("0"),
        networking_capital=Decimal("0"),
        invest_capital=Decimal("0"),
        retained_earnings=Decimal("0"),
        diluted2_eps=Decimal("0"),
        bps=Decimal("0"),
        ocfps=Decimal("0"),
        retainedps=Decimal("0"),
        cfps=Decimal("0"),
        ebit_ps=Decimal("0"),
        fcff_ps=Decimal("0"),
        fcfe_ps=Decimal("0"),
        netprofit_margin=Decimal("0"),
        grossprofit_margin=Decimal("0"),
        cogs_of_sales=Decimal("0"),
        expense_of_sales=Decimal("0"),
        profit_to_gr=Decimal("0"),
        saleexp_to_gr=Decimal("0"),
        adminexp_of_gr=Decimal("0"),
        finaexp_of_gr=Decimal("0"),
        impai_ttm=Decimal("0"),
        gc_of_gr=Decimal("0"),
        op_of_gr=Decimal("0"),
        ebit_of_gr=Decimal("0"),
        roe=Decimal("0"),
        roe_waa=Decimal("0"),
        roe_dt=Decimal("0"),
        roa=Decimal("0"),
        npta=Decimal("0"),
        roic=Decimal("0"),
        roe_yearly=Decimal("0"),
        roa2_yearly=Decimal("0"),
        roe_avg=Decimal("0"),
        opincome_of_ebt=Decimal("0"),
        investincome_of_ebt=Decimal("0"),
        n_op_profit_of_ebt=Decimal("0"),
        tax_to_ebt=Decimal("0"),
        dtprofit_to_profit=Decimal("0"),
        salescash_to_or=Decimal("0"),
        ocf_to_or=Decimal("0"),
        ocf_to_opincome=Decimal("0"),
        capitalized_to_da=Decimal("0"),
        debt_to_assets=Decimal("0"),
        assets_to_eqt=Decimal("0"),
        dp_assets_to_eqt=Decimal("0"),
        ca_to_assets=Decimal("0"),
        nca_to_assets=Decimal("0"),
        tbassets_to_totalassets=Decimal("0"),
        int_to_talcap=Decimal("0"),
        eqt_to_talcapital=Decimal("0"),
        currentdebt_to_debt=Decimal("0"),
        longdeb_to_debt=Decimal("0"),
        ocf_to_shortdebt=Decimal("0"),
        debt_to_eqt=Decimal("0"),
        eqt_to_debt=Decimal("0"),
        eqt_to_interestdebt=Decimal("0"),
        tangibleasset_to_debt=Decimal("0"),
        tangasset_to_intdebt=Decimal("0"),
        tangibleasset_to_netdebt=Decimal("0"),
        ocf_to_debt=Decimal("0"),
        ocf_to_interestdebt=Decimal("0"),
        ocf_to_netdebt=Decimal("0"),
        ebit_to_interest=Decimal("0"),
        longdebt_to_workingcapital=Decimal("0"),
        ebitda_to_debt=Decimal("0"),
        turn_days=Decimal("0"),
        roa_yearly=Decimal("0"),
        roa_dp=Decimal("0"),
        fixed_assets=Decimal("0"),
        profit_prefin_exp=Decimal("0"),
        non_op_profit=Decimal("0"),
        op_to_ebt=Decimal("0"),
        nop_to_ebt=Decimal("0"),
        ocf_to_profit=Decimal("0"),
        cash_to_liqdebt=Decimal("0"),
        cash_to_liqdebt_withinterest=Decimal("0"),
        op_to_liqdebt=Decimal("0"),
        op_to_debt=Decimal("0"),
        roic_yearly=Decimal("0"),
        total_fa_trun=Decimal("0"),
        profit_to_op=Decimal("0"),
        q_opincome=Decimal("0"),
        q_investincome=Decimal("0"),
        q_dtprofit=Decimal("0"),
        q_eps=Decimal("0"),
        q_netprofit_margin=Decimal("0"),
        q_gsprofit_margin=Decimal("0"),
        q_exp_to_sales=Decimal("0"),
        q_profit_to_gr=Decimal("0"),
        q_saleexp_to_gr=Decimal("0"),
        q_adminexp_to_gr=Decimal("0"),
        q_finaexp_to_gr=Decimal("0"),
        q_impair_to_gr_ttm=Decimal("0"),
        q_gc_to_gr=Decimal("0"),
        q_op_to_gr=Decimal("0"),
        q_roe=Decimal("0"),
        q_dt_roe=Decimal("0"),
        q_npta=Decimal("0"),
        q_opincome_to_ebt=Decimal("0"),
        q_investincome_to_ebt=Decimal("0"),
        q_dtprofit_to_profit=Decimal("0"),
        q_salescash_to_or=Decimal("0"),
        q_ocf_to_sales=Decimal("0"),
        q_ocf_to_or=Decimal("0"),
        basic_eps_yoy=Decimal("0"),
        dt_eps_yoy=Decimal("0"),
        cfps_yoy=Decimal("0"),
        op_yoy=Decimal("0"),
        ebt_yoy=Decimal("0"),
        netprofit_yoy=Decimal("0"),
        dt_netprofit_yoy=Decimal("0"),
        ocf_yoy=Decimal("0"),
        roe_yoy=Decimal("0"),
        bps_yoy=Decimal("0"),
        assets_yoy=Decimal("0"),
        eqt_yoy=Decimal("0"),
        tr_yoy=Decimal("0"),
        or_yoy=Decimal("0"),
        q_gr_yoy=Decimal("0"),
        q_gr_qoq=Decimal("0"),
        q_sales_yoy=Decimal("0"),
        q_sales_qoq=Decimal("0"),
        q_op_yoy=Decimal("0"),
        q_op_qoq=Decimal("0"),
        q_profit_yoy=Decimal("0"),
        q_profit_qoq=Decimal("0"),
        q_netprofit_yoy=Decimal("0"),
        q_netprofit_qoq=Decimal("0"),
        equity_yoy=Decimal("0"),
        rd_exp=Decimal("0"),
        update_flag="1"
    )

    return FinancialReport(
        ts_code="000001.SZ",
        report_date=date(2023, 3, 31),
        report_type="1",
        end_type="1",  # 添加 end_type 参数
        income_statement=income_statement,
        balance_sheet=balance_sheet,
        cash_flow_statement=cash_flow_statement,
        financial_indicators=financial_indicators
    )

def test_save_and_get(repository, sample_report):
    """测试保存和获取财务报告"""
    # 保存报告
    repository.save(sample_report)
    
    # 获取报告
    retrieved_report = repository.get(
        sample_report.ts_code,
        sample_report.report_date,
        sample_report.report_type
    )
    
    # 验证获取的数据
    assert retrieved_report is not None
    assert retrieved_report.ts_code == sample_report.ts_code
    assert retrieved_report.report_date == sample_report.report_date
    assert retrieved_report.report_type == sample_report.report_type
    
    # 验证财务报表数据
    assert retrieved_report.income_statement.total_revenue == sample_report.income_statement.total_revenue
    assert retrieved_report.balance_sheet.total_assets == sample_report.balance_sheet.total_assets
    assert retrieved_report.cash_flow_statement.net_profit == sample_report.cash_flow_statement.net_profit
    assert retrieved_report.financial_indicators.eps == sample_report.financial_indicators.eps

def test_get_all(repository, sample_report):
    """测试获取所有财务报告"""
    # 保存报告
    repository.save(sample_report)
    
    # 获取所有报告
    reports = repository.get_all(sample_report.ts_code)
    
    # 验证结果
    assert len(reports) == 1
    assert reports[0].ts_code == sample_report.ts_code
    assert reports[0].report_date == sample_report.report_date

def test_delete(repository, sample_report):
    """测试删除财务报告"""
    # 保存报告
    repository.save(sample_report)
    
    # 删除报告
    result = repository.delete(
        sample_report.ts_code,
        sample_report.report_date,
        sample_report.report_type
    )
    assert result is True
    
    # 验证报告已被删除
    retrieved_report = repository.get(
        sample_report.ts_code,
        sample_report.report_date,
        sample_report.report_type
    )
    assert retrieved_report is None

def test_get_nonexistent(repository):
    """测试获取不存在的财务报告"""
    report = repository.get(
        "000001.SZ",
        date(2023, 12, 31),
        "1"
    )
    assert report is None